spring:
  application:
    name: sobreviventesApi
  datasource:
    url: jdbc:postgresql://localhost:5432/survivor_db
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      open-in-view: false


